### ISSUE TITLE
Review the skipped tests in test_if_config.py --> TestInterfacesConfig class

### ISSUE THREAD

**Issue by j-suarezp** [sbarguil/Testing-framework#11]
## Skipped tests:
- test_if_config_loopback_mode: Execution not tested, lab routers cisco and juniper doesn't allow to change the param
- test_if_config_tpid: Execution not tested, lab routers cisco and juniper doesn't allow to change the param
- test_if_config_type: This test is being skipped. It might need an individual implementation in order to get the prefix of the param tested from the first get config and use it in the edit-config

**Comment by danielhbar** [comment]
@j-suarezp  Fixed.

**Comment by j-suarezp** [comment]
Fixed in #85
