### ISSUE TITLE
Review the skipped tests in test_if_ethernet.py --> TestInterfacesEthernet class

### ISSUE THREAD

**Issue by j-suarezp** [sbarguil/Testing-framework#21]
### Skipped tests:
- if_ethernet_aggregate_id
  - "error in cisco: Error in cisco: RPCError: The requested operation failed."
  - "error in juniper: ncclient.operations.rpc.RPCError: error: invalid interface type: 1 - error: statement creation failed - error: load failure on translation changes")
- if_ethernet_port_speed
  - "error in cisco: ncclient.operations.rpc.RPCError: 'GIRO' detected the 'warning' condition 'The configuration is not supported on this interface"
  - "error in juniper: ncclient.operations.rpc.RPCError: error: invalid interface type: 1 - error: statement creation failed - error: load failure on translation changes")
- if_ethernet_duplex_mode
  - "error in cisco: ncclient.operations.rpc.RPCError: 'GIRO' detected the 'warning' condition 'The configuration is not supported on this interface"
  - "error in juniper: ncclient.operations.rpc.RPCError: error: invalid interface type: 1 - error: statement creation failed - error: load failure on translation changes")
- if_ethernet_auto_negotiate: 
  - "error in cisco: ncclient.operations.rpc.RPCError: 'GIRO' detected the 'warning' condition 'The configuration is not supported on this interface"
  - "error in juniper: ncclient.operations.rpc.RPCError: error: invalid interface type: 1 - error: statement creation failed - error: load failure on translation changes")

### Skipped tests:
- if_ethernet_aggregate_id
  - "error in cisco: Error in cisco: RPCError: The requested operation failed."
  - When there is a aggregate previously created: ncclient.operations.rpc.RPCError: Bundle membership configuration conflicts with underlying interface configuration (either already existing or also present in the same commit). Conflicting: /ipv4/io/address/primary
  - "error in juniper: ncclient.operations.rpc.RPCError: error: invalid interface type: 1 - error: load failure on translation changes")

**Comment by sbarguil** [comment]
I found this error too...

``
error in juniper: ncclient.operations.rpc.RPCError: error: invalid interface type: 1 - error: statement creation failed - error: load failure on translation changes")
``

solved using the rollback configuration on the router

**Comment by sbarguil** [comment]
In cisco....https://bst.cloudapps.cisco.com/bugsearch/bug/CSCva76113/?rfs=iqvred

It seems the auto-negotiation it is not configurable.

**Comment by j-suarezp** [comment]
@sbarguil tests fixed and completed (Tested in juniper):
- if_ethernet_port_speed
- if_ethernet_duplex_mode
- if_ethernet_auto_negotiate

**Comment by j-suarezp** [comment]
#34 Template fixed by @danielhbar

**Comment by j-suarezp** [comment]
Fixed in #97
