### ISSUE TITLE
 Review the skipped tests in test_if_gre.py --> TestInterfacesGre class

### ISSUE THREAD

**Issue by j-suarezp** [sbarguil/Testing-framework#31]
## Skipped tests:

- if_gre_dst
       "It seams devices doesn't support the creation of gre tunnels"
- if_gre_src
       "It seams devices doesn't support the creation of gre tunnels"
- if_gre_ttl
       "It seams devices doesn't support the creation of gre tunnels"
- if_gre_ip_prefix_length
       "It seams devices doesn't support the creation of gre tunnels"
- if_gre_mtu
       "It seams devices doesn't support the creation of gre tunnels"

**Comment by danielhbar** [comment]
@j-suarezp  
The type of tunnel is added and a RPC to create a tunnel before to send this parameters: "if_gre_ip_prefix_length, if_gre_mtu"

**Comment by j-suarezp** [comment]
Fixed in #23
