### ISSUE TITLE
Review the skipped tests in test_if_subif.py --> TestInterfacesSubInterface class

### ISSUE THREAD

**Issue by j-suarezp** [sbarguil/Testing-framework#47]
## Skipped tests
- test_if_subif_ip_state: Before a get to the ip, the subinterface has to be created, so it needs another rpc
- test_if_subif_origin: Before a get to the origin, the subinterface has to be created, so it needs another rpc
- test_if_subif_dhcp_client: An exception has occurred when performing the edit_config operation. ncclient.operations.rpc.RPCError: {'type': 'protocol', 'tag': 'unknown-element', 'app_tag': None, 'severity': 'error', 'info': '<?xml version='1.0' encoding='UTF-8'?><error-info xmlns='urn:ietf:params:xml:ns:netconf:base:1.0'><bad-element>rpc</bad-element>\n</error-info>\n', 'path': '\n    /rpc\n  ', 'message': None}
- test_if_subif_mtu: An exception has occurred when performing the edit_config operation. ncclient.operations.rpc.RPCError: {'type': 'protocol', 'tag': 'unknown-element', 'app_tag': None, 'severity': 'error', 'info': '<?xml version='1.0' encoding='UTF-8'?><error-info xmlns='urn:ietf:params:xml:ns:netconf:base:1.0'><bad-element>rpc</bad-element>\n</error-info>\n', 'path': '\n    /rpc\n  ', 'message': None}

**Comment by danielhbar** [comment]
@j-suarezp  Fixed.

**Comment by j-suarezp** [comment]
Fixed in #87
