### ISSUE TITLE
Review the skipped tests in test_ni_t_ldp.py --> TestNetworkInstancesTLDP class

### ISSUE THREAD

**Issue by j-suarezp** [sbarguil/Testing-framework#55]
# Skipped tests
- test_ni_t_ldp_afi_name: Incomplete template, error: ncclient.operations.rpc.RPCError: /network-instances/network-instance[name='Prueba_LxVPN']/mpls: the 'when' expression './config/type = 'oc-ni-types:DEFAULT_INSTANCE''' failed
- test_ni_t_ldp_remote_address: Incomplete template, error: ncclient.operations.rpc.RPCError: /network-instances/network-instance[name='Prueba_LxVPN']/mpls: the 'when' expression './config/type = 'oc-ni-types:DEFAULT_INSTANCE''' failed
- test_ni_t_ldp_local_address: Incomplete template, error: ncclient.operations.rpc.RPCError: /network-instances/network-instance[name='Prueba_LxVPN']/mpls: the 'when' expression './config/type = 'oc-ni-types:DEFAULT_INSTANCE''' failed
- test_ni_t_ldp_enabled: Incomplete template, error: ncclient.operations.rpc.RPCError: /network-instances/network-instance[name='Prueba_LxVPN']/mpls: the 'when' expression './config/type = 'oc-ni-types:DEFAULT_INSTANCE''' failed

**Comment by danielhbar** [comment]
The parameter "type: "DEFAULT_INSTANCE" is necessary to configure some of MPLS parameters. @j-suarezp

**Comment by j-suarezp** [comment]
Fixed in #90
