### ISSUE TITLE
Review the not implemented tests in test_ni_bgp.py --> TestNetworkInstancesBGP class

### ISSUE THREAD

**Issue by j-suarezp** [sbarguil/Testing-framework#57]
# Not implemented tests

ni | bgp | export-policy
-- | -- | --
ni | bgp | import-policy

We should divide the test cases in two rpcs each one

**Comment by danielhbar** [comment]
Fixed. @j-suarezp

**Comment by j-suarezp** [comment]
Fixed in #91
