### ISSUE TITLE
Review the not implemented tests in test_ni_interface.py --> TestNetworkInstancesInterface class

### ISSUE THREAD

**Issue by j-suarezp** [sbarguil/Testing-framework#58]
# Not implemented tests

ni | interface | interface
-- | -- | --
ni | interface | subinterface

is better if we divide the test case in two rpcs

**Comment by danielhbar** [comment]
The xml "ni_interface_interface.xml" doesnt need to create before an interface, because these already exist like physical ports.

With "ni_interface_subinterface.xml" is necessary the subinterface creation before.

Fixed. @j-suarezp

**Comment by j-suarezp** [comment]
Fixed in #89
