### ISSUE TITLE
Review the not implemented tests in test_ni_rt_policy.py --> TestNetworkInstancesRTPolicy class

### ISSUE THREAD

**Issue by j-suarezp** [sbarguil/Testing-framework#59]
# Not implemented tests

ni | rt_policy | export-policy
-- | -- | --
ni | rt_policy | import-policy

Is better if we divide it in 2 different rpcs for each test cases

**Comment by danielhbar** [comment]
Fixed.

**Comment by j-suarezp** [comment]
Fixed in #88
