### ISSUE TITLE
Review the not implemented tests in test_ni_ospf.py --> TestNetworkInstancesOSPF class

### ISSUE THREAD

**Issue by j-suarezp** [sbarguil/Testing-framework#62]
# Tests skipped
- test_ni_ospf_subinterface: It needs a subinterface to be referenced. error: ncclient.operations.rpc.RPCError: illegal reference /network-instances/network-instance[name='Prueba_LxVPN']/protocols/protocol[identifier='oc-pol-types:OSPF'][name='OSPF_1']/ospfv2/areas/area[identifier='0.0.0.0']/interfaces/interface[id='1']/interface-ref/config/subinterface

**Comment by danielhbar** [comment]
Fixed up, is necessary create a subinterface before to add this parameter in OSPF Configuration.

**Comment by j-suarezp** [comment]
Fixed in #92
