### ISSUE TITLE
Review the not implemented tests in test_qos_scheduler.py --> TestQOSScheduler class

### ISSUE THREAD

**Issue by j-suarezp** [sbarguil/Testing-framework#68]
# Tests skipped
- test_qos_scheduler_queue: Review manually the rpc to see if it works the way it is implemented

**Comment by danielhbar** [comment]
The parameter "input_type: "QUEUE"" is added, fixed up @j-suarezp.

**Comment by j-suarezp** [comment]
Fixed in #95
