### ISSUE TITLE
Review the not implemented tests in test_rp_policy_def.py --> TestRoutingPolicyPolicyDef class

### ISSUE THREAD

**Issue by j-suarezp** [sbarguil/Testing-framework#71]
# Skipped test
- test_rp_policy_def_match_set_options: Error, tag bgp-conditions not known. ncclient.operations.rpc.RPCError: {'type': 'application', 'tag': 'unknown-element', 'app_tag': None, 'severity': 'error', 'info': '<?xml version=1.0 encoding=UTF-8?><error-info xmlns=urn:ietf:params:xml:ns:netconf:base:1.0><bad-element>match-ext-community-set</bad-element>\n</error-info>\n', 'path': '\n    /rpc/edit-config/config/oc-rpol:routing-policy/oc-rpol:policy-definitions/oc-rpol:policy-definition/oc-rpol:statements/oc-rpol:statement/oc-rpol:conditions/oc-bgp-pol:bgp-conditions\n  ', 'message': None}

**Comment by danielhbar** [comment]
Fixed up @j-suarezp, RPC is added before to create a match set options.

          - template: rp_policy_ext_community_set_name.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                   ext_community_set_name: "RT_IMPORT_POLICY"
                   ext_community_member: "65000:103"

**Comment by j-suarezp** [comment]
Fixed in #96
