### ISSUE TITLE
Review the not implemented tests in test_hw_subcomponent.py --> TestHardwareSubcomponent class

### ISSUE THREAD

**Issue by j-suarezp** [sbarguil/Testing-framework#75]
# TEsts skipped
- test_hw_subcomponent_name: We need to create a component for the aggregate it as a subcomponent of another component
- test_hw_subcomponent_name_state: We need to create a component for the aggregate it as a subcomponent of another component and the get operation

**Comment by danielhbar** [comment]
@j-suarezp  Fixed.

**Comment by j-suarezp** [comment]
Fixed in #84
